swagger: "2.0"
info:
  version: "1.0.0"
  title: "Job and Blog API"
servers:
  - url: "https://kassel-2.onrender.com"
paths:
  /blogs:
    get:
      summary: "Get all blogs"
      responses:
        200:
          description: "List of blogs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Blog"
    post:
      summary: "Create a new blog"
      security:
        - bearerAuth: []
      parameters:
        - name: "body"
          in: "body"
          description: "Blog object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Blog"
      responses:
        200:
          description: "Blog created successfully"
        400:
          description: "Invalid input"
  /blogs/{uid}:
    get:
      summary: "Get a blog by its ID"
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the blog to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Blog details"
          schema:
            $ref: "#/definitions/Blog"
        404:
          description: "Blog not found"
    put:
      summary: "Update a blog"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the blog to update"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "Updated blog object"
          required: true
          schema:
            $ref: "#/definitions/Blog"
      responses:
        200:
          description: "Blog updated successfully"
        400:
          description: "Invalid input"
        404:
          description: "Blog not found"
    delete:
      summary: "Delete a blog"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the blog to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Blog deleted successfully"
        404:
          description: "Blog not found"
  /jobs:
    get:
      summary: "Get all jobs"
      responses:
        200:
          description: "List of jobs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Job"
    post:
      summary: "Create a new job"
      security:
        - bearerAuth: []
      parameters:
        - name: "body"
          in: "body"
          description: "Job object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Job"
      responses:
        200:
          description: "Job created successfully"
        400:
          description: "Invalid input"
  /jobs/{uid}:
    get:
      summary: "Get a job by its ID"
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the job to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Job details"
          schema:
            $ref: "#/definitions/Job"
        404:
          description: "Job not found"
    put:
      summary: "Update a job"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the job to update"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "Updated job object"
          required: true
          schema:
            $ref: "#/definitions/Job"
      responses:
        200:
          description: "Job updated successfully"
        400:
          description: "Invalid input"
        404:
          description: "Job not found"
    delete:
      summary: "Delete a job"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the job to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Job deleted successfully"
        404:
          description: "Job not found"
  /job-applications:
    get:
      summary: "Get all job applications"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "List of job applications"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/JobApplication"
  /job-applications/{uid}:
    get:
      summary: "Get a job application by its ID"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the job application to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Job application details"
          schema:
            $ref: "#/definitions/JobApplication"
        404:
          description: "Job application not found"
    delete:
      summary: "Delete a job application"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the job application to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Job application deleted successfully"
        404:
          description: "Job application not found"
  /categories:
    get:
      summary: "Get all categories"
      responses:
        200:
          description: "List of categories"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
    post:
      summary: "Create a new category"
      security:
        - bearerAuth: []
      parameters:
        - name: "body"
          in: "body"
          description: "Category object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: "Category created successfully"
        400:
          description: "Invalid input"
  /categories/{uid}:
    get:
      summary: "Get a category by its ID"
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the category to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Category details"
          schema:
            $ref: "#/definitions/Category"
        404:
          description: "Category not found"
    put:
      summary: "Update a category"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the category to update"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "Updated category object"
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: "Category updated successfully"
        400:
          description: "Invalid input"
        404:
          description: "Category not found"
    delete:
      summary: "Delete a category"
      security:
        - bearerAuth: []
      parameters:
        - name: "uid"
          in: "path"
          description: "ID of the category to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Category deleted successfully"
        404:
          description: "Category not found"
definitions:
  Blog:
    type: "object"
    properties:
      uid:
        type: "string"
        description: "Unique identifier for the blog"
      title:
        type: "string"
        description: "Title of the blog"
      content:
        type: "string"
        description: "Content of the blog"
      author:
        type: "string"
        description: "Author of the blog"
  Job:
    type: "object"
    properties:
      uid:
        type: "string"
        description: "Unique identifier for the job"
      title:
        type: "string"
        description: "Title of the job"
      description:
        type: "string"
        description: "Description of the job"
      location:
        type: "string"
        description: "Location of the job"
  JobApplication:
    type: "object"
    properties:
      uid:
        type: "string"
        description: "Unique identifier for the job application"
      // Define other properties of Job Application
  Category:
    type: "object"
    properties:
      uid:
        type: "string"
        description: "Unique identifier for the category"